resources:
  repositories:
    - repository: templates
      type: git
      name: ccdc-3rd-party/conan-azure-devops
      ref: refs/heads/development

extends:
  template: third-party-library-all-platforms-from-local-recipe.yml@templates
  parameters:
    package: gsoap
    package_version: 2.8.106
    destination_repository: ccdc-3rdparty-conan
    build_types:
      - Release
      - Debug
